---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo2-java-kubernetes-hpa
  namespace: demo2-java-kubernetes
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo2-java-kubernetes-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
